In [1]:
import numpy as np
from pyDOE2 import *
from scipy import stats

# Original Model

In [2]:
sign =  fracfact('a b c ab ac bc abc')
interc = np.ones([8,1])
x = np.hstack((interc, sign))
print("sign table:\n", x)

sign table:
 [[ 1. -1. -1. -1.  1.  1.  1. -1.]
 [ 1.  1. -1. -1. -1. -1.  1.  1.]
 [ 1. -1.  1. -1. -1.  1. -1.  1.]
 [ 1.  1.  1. -1.  1. -1. -1. -1.]
 [ 1. -1. -1.  1.  1. -1. -1.  1.]
 [ 1.  1. -1.  1. -1.  1. -1. -1.]
 [ 1. -1.  1.  1. -1. -1.  1. -1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]]


In [3]:
y = np.array([
    [14, 16, 12],
    [22, 18, 20],
    [11, 15, 19],
    [34, 30, 35],
    [46, 42, 44],
    [58, 62, 60],
    [50, 55, 54],
    [86, 80, 74],
             ])
y_mean = np.mean(y, axis=1)
print("y_bar: ", y_mean)
y_bar = y_mean.reshape([y_mean.shape[0],1])

y_bar:  [14. 20. 15. 33. 44. 60. 53. 80.]


In [4]:
q = 1./8 * np.dot(y_bar.T, x)
print("q: ", q.reshape([8,]))
q = q.reshape([8,1])

q:  [39.875  8.375  5.375 19.375  2.875  2.375  1.875 -0.125]


In [5]:
SSY = np.sum(y ** 2)
SSj = 2**3 * 3 * q**2
SSE = np.sum((y - y_bar)**2)
SST = SSY - SSj[0]

In [6]:
percentage = SSj[1:]/SST[0] * 100
print("percentage variation (%):")
print(np.round(percentage,2).T)

percentage variation (%):
[[14.06  5.79 75.27  1.66  1.13  0.7   0.  ]]


In [7]:
t = stats.t.ppf(1-0.1/2, 2**3 * (3-1))
print("t[1-0.1/2;2^3(3-1)]: ", t)

t[1-0.1/2;2^3(3-1)]:  1.74588367627624


In [8]:
Se = np.sqrt(SSE/(2**3 * (3-1)))
Sqi = Se/np.sqrt(2**3 * 3)

In [9]:
q_lower = q - t * Sqi
q_upper = q + t * Sqi

CI = np.hstack((q_lower,q_upper))
for i in range(len(CI)):
    print("q"+str(i)+": ", CI[i])

q0:  [38.73403685 41.01596315]
q1:  [7.23403685 9.51596315]
q2:  [4.23403685 6.51596315]
q3:  [18.23403685 20.51596315]
q4:  [1.73403685 4.01596315]
q5:  [1.23403685 3.51596315]
q6:  [0.73403685 3.01596315]
q7:  [-1.26596315  1.01596315]


# New Model

In [10]:
sign =  fracfact('a b c ab ac bc')
interc = np.ones([8,1])
x = np.hstack((interc, sign))
print("sign table:\n", x)

sign table:
 [[ 1. -1. -1. -1.  1.  1.  1.]
 [ 1.  1. -1. -1. -1. -1.  1.]
 [ 1. -1.  1. -1. -1.  1. -1.]
 [ 1.  1.  1. -1.  1. -1. -1.]
 [ 1. -1. -1.  1.  1. -1. -1.]
 [ 1.  1. -1.  1. -1.  1. -1.]
 [ 1. -1.  1.  1. -1. -1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]


In [11]:
y = np.array([
    [14, 16, 12],
    [22, 18, 20],
    [11, 15, 19],
    [34, 30, 35],
    [46, 42, 44],
    [58, 62, 60],
    [50, 55, 54],
    [86, 80, 74],
             ])
y_mean = np.mean(y, axis=1)
print("y_bar: ", y_mean)
y_bar = y_mean.reshape([y_mean.shape[0],1])

y_bar:  [14. 20. 15. 33. 44. 60. 53. 80.]


In [12]:
q = 1./7 * np.dot(y_bar.T, x)
print("q: ", q.reshape([7,]))
q = q.reshape([7,1])

q:  [45.57142857  9.57142857  6.14285714 22.14285714  3.28571429  2.71428571
  2.14285714]


In [13]:
SSY = np.sum(y ** 2)
SSj = (2**3-1) * 3 * q**2
SSE = np.sum((y - y_bar)**2)
SST = SSY - SSj[0]

In [14]:
percentage = SSj[1:]/SST[0] * 100
print("percentage variation (%):")
print(np.round(percentage,2).T)

percentage variation (%):
[[ 29.52  12.16 157.99   3.48   2.37   1.48]]


In [15]:
t = stats.t.ppf(1-0.1/2, (2**3-1) * (3-1))
print("t[1-0.1/2;2^3(3-1)]: ", t)

t[1-0.1/2;2^3(3-1)]:  1.7613101357748562


In [16]:
Se = np.sqrt(SSE/((2**3-1) * (3-1)))
Sqi = Se/np.sqrt((2**3-1) * 3)

In [17]:
q_lower = q - t * Sqi
q_upper = q + t * Sqi

CI = np.hstack((q_lower,q_upper))
for i in range(len(CI)):
    print("q"+str(i)+": ", CI[i])

q0:  [44.25594905 46.8869081 ]
q1:  [ 8.25594905 10.8869081 ]
q2:  [4.82737762 7.45833667]
q3:  [20.82737762 23.45833667]
q4:  [1.97023476 4.60119381]
q5:  [1.39880619 4.02976524]
q6:  [0.82737762 3.45833667]
