# Introduction to This Document
This document is a toturial for design of experiments and ANOVA test using python. This instruction consists of these parts:
- Design of experiments in python useing pyDOE
- Conducting t-test in python
- One-way ANOVA test
- Two-way ANOVA test

For more details about the installation of the packages and the examples please refer to these webpages: 

https://pythonhosted.org/pyDOE/index.html

https://pythonfordatascience.org/anova-python/

https://pythonfordatascience.org/anova-2-way-n-way/


# 1- Design of Experiments Using pyDOE

pyDOE is a python package designed to construct experimental designs in python. However, due to some bugs in this package, the fork pyDOE2 package came to solve those issues. You need __numpy__ and __scipy__ to install this package. For more details on installation and examples, please refer to the first reference.

In [1]:
#pip install pyDOE2

In [2]:
from pyDOE2 import *

- __General Full-Factorial (fullfact)__

This kind of design offers full flexibility as to the number of discrete levels for each factor in the design. Its usage is simple:

In [3]:
fullfact([2,3])

array([[0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [0., 2.],
       [1., 2.]])

- __Level Full-Factorial (ff2n)__

This function is a convenience wrapper to _fullfact_ that forces all the factors to have two levels each, you simple tell it how many factors to create a design for:

In [4]:
ff2n(3)

array([[-1., -1., -1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1., -1.],
       [-1., -1.,  1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.],
       [ 1.,  1.,  1.]])

- __Level Fractional-Factorial (fracfact)__

Let’s assume that we just can’t afford (for whatever reason) the number of runs in a full-factorial design. We can systematically decide on a fraction of the full-factorial by allowing some of the factor main effects to be confounded with other factor interaction effects. This is done by defining an alias structure that defines, symbolically, these interactions. These alias structures are written like “C = AB” or “I = ABC”, or “AB = CD”, etc. These define how one column is related to the others.

The example below means that the factor in the third column is confounded with the interaction of the factors in the first two columns.

In [5]:
fracfact('a b ab')

array([[-1., -1.,  1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1.,  1.]])

Fractional factorial designs are usually specified using the notation 2^(k-p), where k is the number of columns and p is the number of effects that are confounded. In terms of resolution level, higher is “better”. The above design would be considered a 2^(3-1) fractional factorial design.

The following is a 2^(7-4) design:

In [6]:
 fracfact('a b ab c ac bc abc')

array([[-1., -1.,  1., -1.,  1.,  1., -1.],
       [ 1., -1., -1., -1., -1.,  1.,  1.],
       [-1.,  1., -1., -1.,  1., -1.,  1.],
       [ 1.,  1.,  1., -1., -1., -1., -1.],
       [-1., -1.,  1.,  1., -1., -1.,  1.],
       [ 1., -1., -1.,  1.,  1., -1., -1.],
       [-1.,  1., -1.,  1., -1.,  1., -1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In order to reduce confounding, we can utilize the _fold_ function:

In [7]:
m = fracfact('a b ab')
print(fold(m))

[[-1. -1.  1.]
 [ 1. -1. -1.]
 [-1.  1. -1.]
 [ 1.  1.  1.]
 [ 1.  1. -1.]
 [-1.  1.  1.]
 [ 1. -1.  1.]
 [-1. -1. -1.]]


Applying the fold to all columns in the design breaks the alias chains between every main factor and two-factor interactions. This means that we can then estimate all the main effects clear of any two-factor interactions. Typically, when all columns are folded, this “upgrades” the resolution of the design.

By default, fold applies the level swapping to all columns, but we can _fold_ specific columns (first column = 0), if desired, by supplying an array to the keyword _columns_:

In [8]:
fold(m, columns=[2])

array([[-1., -1.,  1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1.,  1.],
       [-1., -1., -1.],
       [ 1., -1.,  1.],
       [-1.,  1.,  1.],
       [ 1.,  1., -1.]])

- __Plackett-Burman (pbdesign)__

Another way to generate fractional-factorial designs is through the use of Plackett-Burman designs. These designs are unique in that the number of trial conditions (rows) expands by multiples of four (e.g. 4, 8, 12, etc.). The max number of columns allowed before a design increases the number of rows is always one less than the next higher multiple of four.

For example, one can use up to 3 factors in a design with 4 rows:

In [9]:
pbdesign(3)

array([[-1., -1.,  1.],
       [ 1., -1., -1.],
       [-1.,  1., -1.],
       [ 1.,  1.,  1.]])

## 2- Conducting t-test in Python
The t test (also called Student’s T Test) compares two averages (means) and tells you if they are different from each other. The t test also tells you how significant the differences are; In other words it lets you know if those differences could have happened by chance.

One can calculate the t-statistic itself or use pre-defined python functions. 

Below you can find an example comparing the means of two randomly generated distributions using t-test. You can use the function *stats.ttest_ind* in scipy library to find t statisctics and p value directly.

In [10]:
## Import the packages
import numpy as np
from scipy import stats


## Define 2 random distributions
#Sample Size
N = 10
#Gaussian distributed data with mean = 2 and var = 1
a = np.random.randn(N) + 2
#Gaussian distributed data with with mean = 0 and var = 1
b = np.random.randn(N)


## Calculate the Standard Deviation
#Calculate the variance to get the standard deviation

#For unbiased max likelihood estimate we have to divide the var by N-1, and therefore the parameter ddof = 1
var_a = a.var(ddof=1)
var_b = b.var(ddof=1)

#std deviation
s = np.sqrt((var_a + var_b)/2)



## Calculate the t-statistics
t = (a.mean() - b.mean())/(s*np.sqrt(2/N))


## Compare with the critical t-value
#Degrees of freedom
df = 2*N - 2

#p-value after comparison with the t 
p = 1 - stats.t.cdf(t,df=df)


print("t = " + str(t))
print("p = " + str(2*p))
### You can see that after comparing the t statistic with the critical t value (computed internally) we get a good p value of 0.0005 and thus we reject the null hypothesis and thus it proves that the mean of the two distributions are different and statistically significant.


## Cross Checking with the internal scipy function
t2, p2 = stats.ttest_ind(a,b)
print("t = " + str(t2))
print("p = " + str(p2))

t = 4.854645580238746
p = 0.0001272914872592068
t = 4.854645580238746
p = 0.00012729148725918233


## 3- One-way ANOVA Test
One-way ANOVA test is an extention of t-test and is used when you have more than two groups to compare the means. ANOVA test tells us if there is a difference in the mean somewhere in the model or not.
Below you can find an example of one-way ANOVA using the dataset that is used in the lecture. The dataset cosists of three versions of an algorithm and their measured response time. Each version has been run 5 times. We want to compare the respose times and see if there is a difference between the three levels "R", "V" or "Z".


In [11]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import researchpy as rp
import statsmodels.api as sm
from statsmodels.formula.api import ols
    
import matplotlib.pyplot as plt

# Loading data
algorithm = ['R', 'V', 'Z']
d = {'Group': np.repeat(algorithm,5), 'Response': [144, 120, 176, 288, 144, 101, 144, 211, 288, 72, 130, 180, 141, 374, 302]}
df = pd.DataFrame(data=d)

# Gettin summary statistics
rp.summary_cont(df['Response'])

Variable     N      Mean       SD       SE  95% Conf.  Interval
0  Response  15.0  187.6667  86.7498  22.3987   139.6262  235.7071

In [12]:
# Summary based on algorithm type
rp.summary_cont(df['Response'].groupby(df['Group']))

N   Mean        SD       SE  95% Conf.  Interval
Group                                                  
R      5  174.4   66.5492  29.7617    91.7682  257.0318
V      5  163.2   87.1992  38.9967    54.9279  271.4721
Z      5  225.4  107.5119  48.0808    91.9064  358.8936

- Now we want to conduct a statistical test to see if there is a difference in the means of lidibo for these three doses of the drug. Since the independent variable has more than two categories, we have to use ANOVA test to compare the means. 
- We can do this test in python using *stats.f_oneway()* method which is apart of the scipy.stats library.

In [13]:
# stats.f_oneway(data_group1, data_group2, data_group3, data_groupN)
stats.f_oneway(df['Response'][df['Group'] == 'R'], 
             df['Response'][df['Group'] == 'V'],
             df['Response'][df['Group'] == 'Z'])

F_onewayResult(statistic=0.6989101914688891, pvalue=0.5162767522588427)

- The other way is using statmodels which provides more information about the model.

In [14]:
# model_name = ols('outcome_variable ~ C(group_variable)', data=your_data).fit()
results = ols('Response ~ C(Group)', data=df).fit()
results.summary()

D:\Programmer\Anaconda\lib\site-packages\scipy\stats\stats.py:1604: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=15
  "anyway, n=%i" % int(n))


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               Response   R-squared:                       0.104
Model:                            OLS   Adj. R-squared:                 -0.045
Method:                 Least Squares   F-statistic:                    0.6989
Date:                Sun, 22 Nov 2020   Prob (F-statistic):              0.516
Time:                        20:01:47   Log-Likelihood:                -86.886
No. Observations:                  15   AIC:                             179.8
Df Residuals:                      12   BIC:                             181.9
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept       174.4000     39.658      4.398      0.001      87.993     260.807
C(Group)[T.V]   -11.2000     56.085     -0.200      0.845    -133.398     110.998
C(Group)[T.Z]    51.0000     56.085      0.909      0.381     -71.198     173.198
==============================================================================
Omnibus:                        2.253   Durbin-Watson:                   1.700
Prob(Omnibus):                  0.324   Jarque-Bera (JB):                1.553
Skew:                           0.596   Prob(JB):                        0.460
Kurtosis:                       1.969   Cond. No.                         3.73
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

- You can use the following code to see the ANOVA table: 

In [15]:
aov_table = sm.stats.anova_lm(results, typ=2)
aov_table

sum_sq    df        F    PR(>F)
C(Group)  10992.133333   2.0  0.69891  0.516277
Residual  94365.200000  12.0      NaN       NaN

# Further Learning
To calculate the model effect size, check the assumptions for ANOVA test and conduct the post-hoc test you can refer to the second reference mentioned in the introduction of this document.

# 4- Two-way (N-way) ANOVA
A one-way ANOVA should be used if you have 1 categorical independent variable (IV) with 3+ categories or groups, and 1 continuous dependent variable (DV); this is a 1 factor design.

The two-way ANOVA is an extension to the one-way ANOVA and should be used if you have 2 categorical IVs with 2+ groups, and 1 continuous DV; this is a multi-factor design, specifically a 2 factor design. It’s a 2 factor design, because there are 2 IVs. In the ANOVA framework, IVs are often called factors and each category/group within an IV is called a level. Just as with a one-way ANOVA, a two-way ANOVA tests if there is a difference between the means, but it does not tell which groups differ. To get this information, one has to conduct post-hoc testing.

Below you can find an example that uses the dataset used in the lecture. The data shows the impact of workloads and processors on code size. There are five workloads 'I', 'J', 'K', 'L', 'W' and four processors 'W', 'X', 'Y' and 'Z'. We use the log transformation of the code size here.

In [2]:
import pandas as pd
import researchpy as rp
import seaborn as sns
import numpy as np

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

code_size = [3.8455, 3.8191, 3.8634, 3.5061, 3.4598, 3.5469, 3.6727, 3.6933, 3.6498, 3.7082, 3.7410, 3.6761, 3.8330, 3.8056, 3.8578,
            4.0807, 4.0717, 4.1164, 3.7095, 3.7507, 3.6635, 3.9735, 3.9510, 3.9984, 3.7492, 3.7743, 3.7127, 4.0879, 4.0790, 4.1131,
            4.4633, 4.4321, 4.4779, 3.9523, 3.9066, 3.9857, 4.2953, 4.2866, 4.3247, 4.3491, 4.3636, 4.3313, 4.4558, 4.4289, 4.4851,
            3.9958, 3.9641, 4.0015, 3.6184, 3.6291, 3.6091, 3.8506, 3.8440, 3.8246, 3.7288, 3.7585, 3.6959, 3.9914, 3.9688, 4.0100]
df = pd.DataFrame({'Code_Size': code_size,
                   'Processors': np.repeat(['W', 'X', 'Y', 'Z'], 15),
                   'Workloads': np.r_[np.repeat(['I', 'J', 'K', 'L', 'W'],3),
                                      np.repeat(['I', 'J', 'K', 'L', 'W'],3),
                                      np.repeat(['I', 'J', 'K', 'L', 'W'],3),
                                      np.repeat(['I', 'J', 'K', 'L', 'W'],3)]})


In [17]:
rp.summary_cont(df.groupby(['Processors', 'Workloads']))['Code_Size']

N    Mean      SD      SE  95% Conf.  Interval
Processors Workloads                                                
W          I          3  3.8427  0.0223  0.0129     3.7873    3.8980
           J          3  3.5043  0.0436  0.0252     3.3960    3.6125
           K          3  3.6719  0.0218  0.0126     3.6179    3.7260
           L          3  3.7084  0.0325  0.0187     3.6278    3.7890
           W          3  3.8321  0.0261  0.0151     3.7673    3.8970
X          I          3  4.0896  0.0236  0.0136     4.0309    4.1483
           J          3  3.7079  0.0436  0.0252     3.5995    3.8163
           K          3  3.9743  0.0237  0.0137     3.9154    4.0332
           L          3  3.7454  0.0310  0.0179     3.6685    3.8223
           W          3  4.0933  0.0177  0.0102     4.0494    4.1373
Y          I          3  4.4578  0.0234  0.0135     4.3996    4.5159
           J          3  3.9482  0.0397  0.0229     3.8496    4.0468
           K          3  4.3022  0.0200  0.0115     4.2526    4.3518
           L          3  4.3480  0.0162  0.0093     4.3078    4.3882
           W          3  4.4566  0.0281  0.0162     4.3868    4.5264
Z          I          3  3.9871  0.0202  0.0116     3.9371    4.0372
           J          3  3.6189  0.0100  0.0058     3.5940    3.6437
           K          3  3.8397  0.0135  0.0078     3.8062    3.8733
           L          3  3.7277  0.0313  0.0181     3.6499    3.8055
           W          3  3.9901  0.0206  0.0119     3.9388    4.0413

In [18]:
df.head()

Code_Size Processors Workloads
0     3.8455          W         I
1     3.8191          W         I
2     3.8634          W         I
3     3.5061          W         J
4     3.4598          W         J

In [19]:
model = ols('Code_Size ~ C(Processors)*C(Workloads)', df).fit()

# Seeing if the overall model is significant
print(f"Overall model F({model.df_model: .0f},{model.df_resid: .0f}) = {model.fvalue: .3f}, p = {model.f_pvalue: .4f}")

Overall model F( 19, 40) =  318.779, p =  0.0000


In [20]:
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:              Code_Size   R-squared:                       0.993
Model:                            OLS   Adj. R-squared:                  0.990
Method:                 Least Squares   F-statistic:                     318.8
Date:                Sun, 22 Nov 2020   Prob (F-statistic):           1.17e-37
Time:                        20:01:47   Log-Likelihood:                 143.76
No. Observations:                  60   AIC:                            -247.5
Df Residuals:                      40   BIC:                            -205.6
Df Model:                          19                                         
Covariance Type:            nonrobust                                         
========================================================================================================
                                           coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
Intercept                                3.8427      0.016    246.591      0.000       3.811       3.874
C(Processors)[T.X]                       0.2469      0.022     11.205      0.000       0.202       0.291
C(Processors)[T.Y]                       0.6151      0.022     27.911      0.000       0.571       0.660
C(Processors)[T.Z]                       0.1445      0.022      6.555      0.000       0.100       0.189
C(Workloads)[T.J]                       -0.3384      0.022    -15.355      0.000      -0.383      -0.294
C(Workloads)[T.K]                       -0.1707      0.022     -7.747      0.000      -0.215      -0.126
C(Workloads)[T.L]                       -0.1342      0.022     -6.091      0.000      -0.179      -0.090
C(Workloads)[T.W]                       -0.0105      0.022     -0.478      0.635      -0.055       0.034
C(Processors)[T.X]:C(Workloads)[T.J]    -0.0433      0.031     -1.389      0.172      -0.106       0.020
C(Processors)[T.Y]:C(Workloads)[T.J]    -0.1712      0.031     -5.492      0.000      -0.234      -0.108
C(Processors)[T.Z]:C(Workloads)[T.J]    -0.0299      0.031     -0.958      0.344      -0.093       0.033
C(Processors)[T.X]:C(Workloads)[T.K]     0.0554      0.031      1.779      0.083      -0.008       0.118
C(Processors)[T.Y]:C(Workloads)[T.K]     0.0152      0.031      0.487      0.629      -0.048       0.078
C(Processors)[T.Z]:C(Workloads)[T.K]     0.0233      0.031      0.749      0.458      -0.040       0.086
C(Processors)[T.X]:C(Workloads)[T.L]    -0.2100      0.031     -6.737      0.000      -0.273      -0.147
C(Processors)[T.Y]:C(Workloads)[T.L]     0.0245      0.031      0.785      0.437      -0.039       0.087
C(Processors)[T.Z]:C(Workloads)[T.L]    -0.1252      0.031     -4.016      0.000      -0.188      -0.062
C(Processors)[T.X]:C(Workloads)[T.W]     0.0143      0.031      0.458      0.650      -0.049       0.077
C(Processors)[T.Y]:C(Workloads)[T.W]     0.0094      0.031      0.301      0.765      -0.054       0.072
C(Processors)[T.Z]:C(Workloads)[T.W]     0.0135      0.031      0.432      0.668      -0.050       0.076
==============================================================================
Omnibus:                        2.384   Durbin-Watson:                   2.945
Prob(Omnibus):                  0.304   Jarque-Bera (JB):                1.481
Skew:                          -0.082   Prob(JB):                        0.477
Kurtosis:                       2.248   Cond. No.                         27.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

- You can use the following function to see the two-way ANOVA table as below:

In [21]:
res = sm.stats.anova_lm(model, typ= 2)
res

sum_sq    df            F        PR(>F)
C(Processors)               2.929369   3.0  1340.358949  3.778409e-40
C(Workloads)                1.328227   4.0   455.806817  8.894693e-33
C(Processors):C(Workloads)  0.154801  12.0    17.707660  2.326800e-12
Residual                    0.029140  40.0          NaN           NaN